-- LogLM schema
--
-- Extensions:
--   pgcrypto  – gen_random_uuid() for chat sessions + secure token digests
--   pg_trgm   – fast ILIKE search on message / host columns
--   vector    – pgvector for embedding-based RAG. Optional: CREATE EXTENSION
--               fails silently on a base postgres image; LogLM falls back to
--               BYTEA storage when the extension is absent.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
DO $ext$ BEGIN
    BEGIN
        CREATE EXTENSION IF NOT EXISTS vector;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'pgvector not available, embedding cache will use BYTEA fallback';
    END;
END $ext$;

-- ═══════════════════════════════════════════════════════════════════════════
-- Raw parsed events — range-partitioned by month on timestamp.
-- Benefits: instant DROP of old months (vs slow DELETE), per-partition
-- vacuuming, partition pruning on all time-range queries.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE SEQUENCE IF NOT EXISTS events_id_seq;

CREATE TABLE IF NOT EXISTS events (
    id          BIGINT NOT NULL DEFAULT nextval('events_id_seq'),
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    host        TEXT NOT NULL,
    source      TEXT NOT NULL,        -- syslog / nginx / firewall / snmp / librenms
    severity    TEXT NOT NULL,
    program     TEXT,
    message     TEXT NOT NULL,
    structured  JSONB DEFAULT '{}',
    verdict     TEXT NOT NULL,        -- keep / store
    event_hash  BYTEA                 -- xxhash128 for idempotent inserts + signature lookup
) PARTITION BY RANGE (timestamp);

ALTER SEQUENCE events_id_seq OWNED BY events.id;

CREATE INDEX IF NOT EXISTS idx_events_ts_brin       ON events USING BRIN (timestamp) WITH (pages_per_range = 32);
CREATE INDEX IF NOT EXISTS idx_events_host          ON events (host);
CREATE INDEX IF NOT EXISTS idx_events_host_ts       ON events (host, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_structured    ON events USING GIN (structured jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_events_msg_trgm      ON events USING GIN (message gin_trgm_ops);
CREATE UNIQUE INDEX IF NOT EXISTS uq_events_hash    ON events (event_hash, timestamp) WHERE event_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_events_ts_sev       ON events (timestamp DESC, severity);

-- Alerts generated by LLM
CREATE TABLE IF NOT EXISTS alerts (
    id                  BIGSERIAL PRIMARY KEY,
    timestamp           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    severity            TEXT NOT NULL,
    title               TEXT NOT NULL,
    description         TEXT,
    affected_hosts      TEXT[],
    recommended_action  TEXT,
    false_positive_risk TEXT,
    event_count         INT,
    seen_count          INT DEFAULT 1,
    cooldown_key        TEXT,
    acknowledged        BOOLEAN DEFAULT FALSE,
    raw_result          JSONB DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_alerts_timestamp     ON alerts (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_last_seen     ON alerts (last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_severity_ts   ON alerts (severity, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_cooldown_key  ON alerts (cooldown_key, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_unacked       ON alerts (last_seen DESC) WHERE NOT acknowledged;

-- Service aliases: map raw hostnames/IPs to friendly names
CREATE TABLE IF NOT EXISTS service_aliases (
    id          SERIAL PRIMARY KEY,
    raw_name    TEXT NOT NULL UNIQUE,  -- IP or hostname as it appears in logs
    alias       TEXT NOT NULL,         -- human-friendly name
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Service status derived from recent events
-- Updated by processor when a service's state changes
CREATE TABLE IF NOT EXISTS service_status (
    id              SERIAL PRIMARY KEY,
    service_name    TEXT NOT NULL UNIQUE,
    host            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'unknown',  -- ok / warning / error / unknown
    last_event      TIMESTAMPTZ,
    last_message    TEXT,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Chat conversations (memory system)
CREATE TABLE IF NOT EXISTS chat_sessions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       TEXT NOT NULL DEFAULT 'New conversation',
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          BIGSERIAL PRIMARY KEY,
    session_id  UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL,          -- user / assistant
    content     TEXT NOT NULL,
    context_summary TEXT,               -- snapshot of what the LLM was shown
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_session ON chat_messages (session_id, created_at);

-- Periodic summaries used as LLM memory / context compression
-- The analyzer writes one every N minutes summarising recent activity
CREATE TABLE IF NOT EXISTS memory_summaries (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    period_start TIMESTAMPTZ NOT NULL,
    period_end   TIMESTAMPTZ NOT NULL,
    summary     TEXT NOT NULL,
    key_events  JSONB DEFAULT '[]',     -- notable event IDs + one-liners
    stats       JSONB DEFAULT '{}'      -- event counts, top hosts, severity breakdown
);

CREATE INDEX idx_memory_summaries_ts ON memory_summaries (timestamp DESC);

-- SNMP metric history (rolled up from raw polls)
CREATE SEQUENCE IF NOT EXISTS snmp_metrics_id_seq;

CREATE TABLE IF NOT EXISTS snmp_metrics (
    id          BIGINT NOT NULL DEFAULT nextval('snmp_metrics_id_seq'),
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    host        TEXT NOT NULL,
    sys_name    TEXT,
    avg_cpu     REAL,
    wifi_clients INT,
    interfaces_up   INT,
    interfaces_down INT,
    total_in_bps    REAL,
    total_out_bps   REAL,
    total_errors    REAL,
    raw_data    JSONB DEFAULT '{}'
) PARTITION BY RANGE (timestamp);

ALTER SEQUENCE snmp_metrics_id_seq OWNED BY snmp_metrics.id;

CREATE INDEX IF NOT EXISTS idx_snmp_ts_brin      ON snmp_metrics USING BRIN (timestamp) WITH (pages_per_range = 32);
CREATE INDEX IF NOT EXISTS idx_snmp_host_ts      ON snmp_metrics (host, timestamp DESC);

-- SNMP devices managed via the web UI / pulled from LibreNMS.
-- The snmp service reads from this table on every poll cycle so admin
-- changes take effect without a restart.
CREATE TABLE IF NOT EXISTS snmp_devices (
    id          SERIAL PRIMARY KEY,
    host        TEXT NOT NULL UNIQUE,
    port        INT  NOT NULL DEFAULT 161,
    community   TEXT NOT NULL DEFAULT 'public',
    device_type TEXT NOT NULL DEFAULT 'auto',  -- auto/router/switch/ap/firewall/server
    label       TEXT,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    source      TEXT NOT NULL DEFAULT 'manual', -- manual/env/librenms
    last_polled TIMESTAMPTZ,
    last_status TEXT,                            -- ok / error / unreachable
    last_error  TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_snmp_devices_enabled ON snmp_devices (enabled);

-- User feedback for AI training (click important / click ignore)
CREATE TABLE IF NOT EXISTS event_feedback (
    id          BIGSERIAL PRIMARY KEY,
    event_id    BIGINT,                  -- optional link to events.id
    host        TEXT,
    program     TEXT,
    pattern     TEXT NOT NULL,           -- message substring / regex fragment
    verdict     TEXT NOT NULL,           -- important / ignore
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_feedback_verdict ON event_feedback (verdict);
CREATE INDEX idx_feedback_host_program ON event_feedback (host, program);

-- Per-host metadata: tags, notes, pin state.
-- Host is the natural key; we never delete history when a tag changes.
CREATE TABLE IF NOT EXISTS host_metadata (
    host        TEXT PRIMARY KEY,
    tags        TEXT[] NOT NULL DEFAULT '{}',
    notes       TEXT,
    pinned      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_host_metadata_pinned ON host_metadata (pinned) WHERE pinned;
CREATE INDEX IF NOT EXISTS idx_host_metadata_tags   ON host_metadata USING GIN (tags);

-- Topology graph: nodes are hosts (one row per host) with a saved
-- position (x,y), color and icon hint. Edges link two hosts.
CREATE TABLE IF NOT EXISTS topology_nodes (
    host        TEXT PRIMARY KEY,
    label       TEXT,
    icon        TEXT NOT NULL DEFAULT 'server',  -- router/switch/ap/firewall/server/cloud
    color       TEXT,
    x           REAL,
    y           REAL,
    pinned      BOOLEAN NOT NULL DEFAULT FALSE,
    notes       TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS topology_edges (
    id          SERIAL PRIMARY KEY,
    from_host   TEXT NOT NULL,
    to_host     TEXT NOT NULL,
    label       TEXT,
    color       TEXT,
    weight      REAL NOT NULL DEFAULT 1.0,
    auto        BOOLEAN NOT NULL DEFAULT FALSE,  -- true = auto-discovered
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (from_host, to_host)
);
CREATE INDEX IF NOT EXISTS idx_topology_edges_from ON topology_edges (from_host);
CREATE INDEX IF NOT EXISTS idx_topology_edges_to   ON topology_edges (to_host);

-- Retention policies: each row prunes a slice of one table.
-- The processor runs them hourly. filter_clause is appended to the
-- WHERE on top of the timestamp guard.
CREATE TABLE IF NOT EXISTS retention_policies (
    id              SERIAL PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    table_name      TEXT NOT NULL,
    filter_clause   TEXT,            -- optional extra SQL WHERE fragment
    retention_days  INT  NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    last_run        TIMESTAMPTZ,
    last_deleted    BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO retention_policies (name, table_name, filter_clause, retention_days) VALUES
    ('events_drop',       'events',           'verdict = ''drop''',                         7),
    ('events_store',      'events',           'verdict = ''store''',                        30),
    ('events_keep',       'events',           'verdict = ''keep''',                         90),
    ('alerts_old',        'alerts',           'acknowledged = TRUE OR severity = ''info''', 365),
    ('snmp_metrics_old',  'snmp_metrics',     NULL,                                          90),
    ('memory_summaries',  'memory_summaries', NULL,                                          365),
    ('firewall_flows_old','firewall_flows',   NULL,                                          30),
    ('anomaly_old',       'anomaly_detections','acknowledged = TRUE',                       60)
ON CONFLICT (name) DO NOTHING;

-- ── Firewall flows: structured row per parsed firewall event ─────────────────
-- Stores the denormalised flow so we can aggregate (top blocked sources, most
-- targeted ports, external scanners, concerning outbound flows, etc.) without
-- having to re-parse the raw message from the events table.
CREATE SEQUENCE IF NOT EXISTS firewall_flows_id_seq;

CREATE TABLE IF NOT EXISTS firewall_flows (
    id              BIGINT NOT NULL DEFAULT nextval('firewall_flows_id_seq'),
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    host            TEXT NOT NULL,
    action          TEXT NOT NULL,
    blocked         BOOLEAN NOT NULL DEFAULT FALSE,
    direction       TEXT,
    src_ip          INET,
    dst_ip          INET,
    src_port        INT,
    dst_port        INT,
    proto           TEXT,
    in_iface        TEXT,
    out_iface       TEXT,
    port_name       TEXT,
    concerning      BOOLEAN NOT NULL DEFAULT FALSE,
    concerning_reasons TEXT[] NOT NULL DEFAULT '{}',
    event_id        BIGINT
) PARTITION BY RANGE (timestamp);

ALTER SEQUENCE firewall_flows_id_seq OWNED BY firewall_flows.id;

CREATE INDEX IF NOT EXISTS idx_ff_ts_brin      ON firewall_flows USING BRIN (timestamp) WITH (pages_per_range = 32);
CREATE INDEX IF NOT EXISTS idx_ff_host         ON firewall_flows (host, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_ff_src          ON firewall_flows (src_ip);
CREATE INDEX IF NOT EXISTS idx_ff_dst_port     ON firewall_flows (dst_port) WHERE blocked;
CREATE INDEX IF NOT EXISTS idx_ff_concerning   ON firewall_flows (timestamp DESC) WHERE concerning;

-- ── Event signatures: baseline for anomaly learning ──────────────────────────
-- Normalised message signature per host+program. first_seen anchors the
-- "is this new?" check, count + daily rollups drive rate-spike detection.
CREATE TABLE IF NOT EXISTS event_signatures (
    id              BIGSERIAL PRIMARY KEY,
    signature       TEXT NOT NULL,
    host            TEXT NOT NULL,
    program         TEXT NOT NULL,
    severity        TEXT NOT NULL,
    sample_message  TEXT,
    first_seen      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    total_count     BIGINT NOT NULL DEFAULT 1,
    -- Sliding-window counts (updated in-place; cheaper than a full history table)
    count_1h        BIGINT NOT NULL DEFAULT 1,
    count_24h       BIGINT NOT NULL DEFAULT 1,
    window_1h_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    window_24h_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    baseline_per_hour REAL NOT NULL DEFAULT 0,  -- learned rolling mean
    baseline_samples INT NOT NULL DEFAULT 0,
    UNIQUE (signature, host, program)
);
CREATE INDEX IF NOT EXISTS idx_sig_last_seen ON event_signatures (last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_sig_first_seen ON event_signatures (first_seen DESC);
CREATE INDEX IF NOT EXISTS idx_sig_host ON event_signatures (host);

-- ── Anomaly detections: things the baseline flagged as weird ─────────────────
CREATE TABLE IF NOT EXISTS anomaly_detections (
    id              BIGSERIAL PRIMARY KEY,
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    kind            TEXT NOT NULL,          -- new_signature / rate_spike / concerning_flow
    host            TEXT NOT NULL,
    program         TEXT,
    signature       TEXT,
    severity        TEXT NOT NULL DEFAULT 'warning',
    title           TEXT NOT NULL,
    description     TEXT,
    sample          TEXT,
    baseline        REAL,
    observed        REAL,
    acknowledged    BOOLEAN NOT NULL DEFAULT FALSE,
    raw             JSONB DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_anom_ts   ON anomaly_detections (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_anom_host ON anomaly_detections (host);
CREATE INDEX IF NOT EXISTS idx_anom_kind ON anomaly_detections (kind, timestamp DESC);

-- ═══════════════════════════════════════════════════════════════════════════
-- Security / auth
-- ═══════════════════════════════════════════════════════════════════════════
-- Local user accounts for the web UI. Password is a bcrypt/argon2 hash.
-- Roles: admin (can manage users, retention, devices), viewer (read-only).
-- The first bootstrap admin is seeded by web/app/auth.py on startup if the
-- table is empty AND LOGLM_BOOTSTRAP_ADMIN_PASSWORD is set in the env.
CREATE TABLE IF NOT EXISTS users (
    id            SERIAL PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'viewer',  -- admin | viewer
    disabled      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login    TIMESTAMPTZ,
    totp_secret   TEXT,                              -- reserved for 2FA upgrade
    CHECK (role IN ('admin', 'viewer'))
);

-- Server-side sessions backed by itsdangerous cookies. Stored only as SHA-256
-- token hash so a database leak can't resurrect a live session.
CREATE TABLE IF NOT EXISTS user_sessions (
    id          BIGSERIAL PRIMARY KEY,
    user_id     INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  BYTEA NOT NULL UNIQUE,
    ip          INET,
    user_agent  TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expire ON user_sessions (expires_at) WHERE NOT revoked;

-- Long-lived API keys for scripted ingest / Grafana / custom dashboards.
-- Only the SHA-256 of the secret is stored.
CREATE TABLE IF NOT EXISTS api_keys (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL,
    key_prefix  TEXT NOT NULL UNIQUE,    -- first 8 chars of the raw key for listing
    key_hash    BYTEA NOT NULL UNIQUE,
    scopes      TEXT[] NOT NULL DEFAULT '{read}',  -- read | ingest | admin
    created_by  INT REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used   TIMESTAMPTZ,
    expires_at  TIMESTAMPTZ,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE
);

-- Audit log for admin-sensitive actions. Append-only. The web UI refuses to
-- delete rows from this table; a retention policy can purge old entries by age.
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id     INT REFERENCES users(id) ON DELETE SET NULL,
    username    TEXT,                 -- preserved even if user row is deleted
    action      TEXT NOT NULL,        -- login / alert_ack / alert_ignore / retention_write / device_add / ...
    target      TEXT,                 -- free-form: "alert:1234", "device:routerA"
    ip          INET,
    detail      JSONB DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_audit_ts   ON audit_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log (user_id, timestamp DESC);

-- ═══════════════════════════════════════════════════════════════════════════
-- Sigma rule engine
-- ═══════════════════════════════════════════════════════════════════════════
-- Offline Sigma ruleset, loaded from /app/sigma_rules at startup. Rows are
-- upserted by (rule_id, version_hash), disabled rows are skipped at match time.
CREATE TABLE IF NOT EXISTS sigma_rules (
    id            SERIAL PRIMARY KEY,
    rule_id       TEXT NOT NULL UNIQUE,  -- UUID from the Sigma YAML "id:" field
    title         TEXT NOT NULL,
    status        TEXT,                   -- stable | test | experimental | deprecated
    level         TEXT,                   -- informational | low | medium | high | critical
    logsource     JSONB DEFAULT '{}',
    tags          TEXT[] NOT NULL DEFAULT '{}',
    yaml          TEXT NOT NULL,
    compiled      JSONB NOT NULL DEFAULT '{}',  -- precompiled match structure (fields → conditions)
    version_hash  TEXT NOT NULL,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sigma_rules_enabled ON sigma_rules (enabled, level);
CREATE INDEX IF NOT EXISTS idx_sigma_rules_tags    ON sigma_rules USING GIN (tags);

-- When a rule fires we record the hit for later review + for the UI's "top
-- rules this week" widget. Not the actual event (that's in events already).
CREATE TABLE IF NOT EXISTS sigma_hits (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rule_id     TEXT NOT NULL,
    rule_level  TEXT,
    host        TEXT,
    program     TEXT,
    event_id    BIGINT,
    summary     TEXT,
    raw         JSONB DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_sigma_hits_ts     ON sigma_hits (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_sigma_hits_rule   ON sigma_hits (rule_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_sigma_hits_host   ON sigma_hits (host);

-- ═══════════════════════════════════════════════════════════════════════════
-- Threat intelligence cache (GeoIP + AbuseIPDB + GreyNoise + blocklists)
-- All lookups are cached locally so we never rely on a live upstream and
-- never leak the network's browsing patterns to a third party.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS geoip_cache (
    ip          INET PRIMARY KEY,
    country     TEXT,
    country_iso TEXT,
    city        TEXT,
    lat         REAL,
    lon         REAL,
    asn         INT,
    asn_org     TEXT,
    source      TEXT NOT NULL DEFAULT 'maxmind',
    looked_up   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS threat_intel (
    ip           INET PRIMARY KEY,
    reputation   INT,                      -- 0..100 (higher = worse)
    categories   TEXT[] NOT NULL DEFAULT '{}',  -- scanner | bruteforce | malware | c2 | tor | vpn
    source       TEXT NOT NULL,           -- abuseipdb | greynoise | firehol | manual
    detail       JSONB DEFAULT '{}',
    looked_up    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_threat_intel_rep ON threat_intel (reputation DESC) WHERE reputation > 0;
CREATE INDEX IF NOT EXISTS idx_threat_intel_src ON threat_intel (source);

-- Local blocklists imported offline (firehol, spamhaus drop, etc.). The
-- import script lives at scripts/update_blocklists.py and can be cronned.
CREATE TABLE IF NOT EXISTS blocklist_entries (
    id          BIGSERIAL PRIMARY KEY,
    cidr        CIDR NOT NULL,
    list_name   TEXT NOT NULL,
    category    TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (cidr, list_name)
);
CREATE INDEX IF NOT EXISTS idx_blocklist_cidr ON blocklist_entries USING GIST (cidr inet_ops);

-- ═══════════════════════════════════════════════════════════════════════════
-- Embedding cache — semantic search + RAG over past events
-- ═══════════════════════════════════════════════════════════════════════════
-- Stores one row per unique message signature. Vectors are either pgvector's
-- VECTOR type (when the extension is available) or BYTEA (fallback). The
-- analyzer's vector_cache module handles either.
DO $emb$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
        CREATE TABLE IF NOT EXISTS event_embeddings (
            id            BIGSERIAL PRIMARY KEY,
            signature     TEXT NOT NULL UNIQUE,
            sample        TEXT NOT NULL,
            embedding     VECTOR(768),     -- nomic-embed-text dim
            verdict       TEXT,             -- last-known user verdict for this sig
            hit_count     BIGINT NOT NULL DEFAULT 1,
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
        BEGIN
            CREATE INDEX IF NOT EXISTS idx_event_emb_ivfflat
                ON event_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
        EXCEPTION WHEN OTHERS THEN
            -- ivfflat needs ANALYZE data; the cold index can be added later.
            NULL;
        END;
    ELSE
        CREATE TABLE IF NOT EXISTS event_embeddings (
            id            BIGSERIAL PRIMARY KEY,
            signature     TEXT NOT NULL UNIQUE,
            sample        TEXT NOT NULL,
            embedding     BYTEA,
            verdict       TEXT,
            hit_count     BIGINT NOT NULL DEFAULT 1,
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    END IF;
END $emb$;

-- ═══════════════════════════════════════════════════════════════════════════
-- Host baselines — richer version of event_signatures, keeps numeric features
-- for the isolation forest / multivariate anomaly detector.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS host_baselines (
    id             BIGSERIAL PRIMARY KEY,
    host           TEXT NOT NULL,
    hour_of_day    SMALLINT NOT NULL,    -- 0..23, for seasonality
    day_of_week    SMALLINT NOT NULL,    -- 0..6
    events_mean    REAL NOT NULL DEFAULT 0,
    events_std     REAL NOT NULL DEFAULT 0,
    errors_mean    REAL NOT NULL DEFAULT 0,
    cpu_mean       REAL,
    in_bps_mean    REAL,
    out_bps_mean   REAL,
    samples        INT NOT NULL DEFAULT 0,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (host, hour_of_day, day_of_week)
);
CREATE INDEX IF NOT EXISTS idx_host_baselines_host ON host_baselines (host);

-- Multivariate / change-point detections that couldn't be mapped to a single
-- signature. One row per (host, metric, detection_time).
CREATE TABLE IF NOT EXISTS host_anomalies (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    host        TEXT NOT NULL,
    detector    TEXT NOT NULL,            -- iforest | changepoint | stl | seasonality
    metric      TEXT,
    score       REAL,
    description TEXT,
    detail      JSONB DEFAULT '{}',
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_host_anom_ts ON host_anomalies (timestamp DESC);

-- ═══════════════════════════════════════════════════════════════════════════
-- Playbooks — user-defined response scripts runnable from the alerts page.
-- NEVER executes shell on the host; only predefined safe actions (webhook,
-- notify, tag host, create ticket) plus user-supplied command whitelists.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS playbooks (
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL UNIQUE,
    description   TEXT,
    match_filter  JSONB NOT NULL DEFAULT '{}',   -- {"severity": ["high"], "title_regex": "..."}
    actions       JSONB NOT NULL DEFAULT '[]',   -- [{"type": "webhook", "url": "..."}, ...]
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_by    INT REFERENCES users(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS playbook_runs (
    id          BIGSERIAL PRIMARY KEY,
    playbook_id INT NOT NULL REFERENCES playbooks(id) ON DELETE CASCADE,
    alert_id    BIGINT,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status      TEXT NOT NULL DEFAULT 'pending',  -- pending | ok | error | dryrun
    log         TEXT
);
CREATE INDEX IF NOT EXISTS idx_playbook_runs_ts ON playbook_runs (started_at DESC);

-- ═══════════════════════════════════════════════════════════════════════════
-- LLDP / CDP neighbour learning — used by auto-topology discovery.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS lldp_neighbours (
    id            BIGSERIAL PRIMARY KEY,
    local_host    TEXT NOT NULL,
    local_port    TEXT,
    remote_host   TEXT,
    remote_port   TEXT,
    remote_mac    TEXT,
    remote_ip     INET,
    capabilities  TEXT[],
    last_seen     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (local_host, local_port, remote_host)
);
CREATE INDEX IF NOT EXISTS idx_lldp_local ON lldp_neighbours (local_host);

-- ═══════════════════════════════════════════════════════════════════════════
-- Backup log — tracks pg_dump + redis RDB snapshots taken by scripts/backup.py
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS backup_log (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    kind        TEXT NOT NULL,           -- postgres | redis | full
    destination TEXT NOT NULL,
    size_bytes  BIGINT,
    duration_s  REAL,
    status      TEXT NOT NULL,           -- ok | error
    detail      TEXT
);
CREATE INDEX IF NOT EXISTS idx_backup_log_ts ON backup_log (timestamp DESC);

-- ═══════════════════════════════════════════════════════════════════════════
-- Distilled classifier state — the XGBoost model that learns from
-- event_feedback rows and runs in microseconds in the processor's hot path.
-- One-row table keyed on model_name; the processor hot-reloads whenever
-- updated_at changes.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS ml_models (
    name          TEXT PRIMARY KEY,
    kind          TEXT NOT NULL,          -- xgboost | sklearn | iforest
    payload       BYTEA NOT NULL,         -- joblib pickle
    vocab         JSONB NOT NULL DEFAULT '{}',
    metrics       JSONB NOT NULL DEFAULT '{}',
    trained_rows  INT NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Bloom filter state — "have we seen this signature in the last hour?" fast
-- path. Persisted so a processor restart doesn't lose the membership set.
CREATE TABLE IF NOT EXISTS bloom_state (
    name        TEXT PRIMARY KEY,
    payload     BYTEA NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Default retention policies for the new tables.
INSERT INTO retention_policies (name, table_name, filter_clause, retention_days) VALUES
    ('sigma_hits_old',   'sigma_hits',      NULL, 90),
    ('audit_log_old',    'audit_log',       NULL, 365),
    ('host_anomalies',   'host_anomalies',  'acknowledged = TRUE', 60),
    ('playbook_runs',    'playbook_runs',   NULL, 90),
    ('backup_log_old',   'backup_log',      NULL, 365)
ON CONFLICT (name) DO NOTHING;


-- ═══════════════════════════════════════════════════════════════════════════
-- Partition management — auto-creates monthly partitions for the three
-- high-volume partitioned tables (events, firewall_flows, snmp_metrics).
-- Called by the processor's partition_loop every hour.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION create_monthly_partitions(
    target_table TEXT,
    months_ahead INT DEFAULT 2
) RETURNS INT AS $$
DECLARE
    start_date DATE;
    end_date   DATE;
    part_name  TEXT;
    created    INT := 0;
    i          INT;
BEGIN
    FOR i IN -1..months_ahead LOOP
        start_date := DATE_TRUNC('month', CURRENT_DATE + (i || ' months')::INTERVAL);
        end_date   := start_date + '1 month'::INTERVAL;
        part_name  := target_table || '_y' || TO_CHAR(start_date, 'YYYY') || 'm' || TO_CHAR(start_date, 'MM');

        IF NOT EXISTS (
            SELECT 1 FROM pg_class WHERE relname = part_name
        ) THEN
            EXECUTE FORMAT(
                'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                part_name, target_table, start_date, end_date
            );
            created := created + 1;
        END IF;
    END LOOP;
    RETURN created;
END;
$$ LANGUAGE plpgsql;

-- Create initial partitions (current month + 2 ahead + 1 behind).
SELECT create_monthly_partitions('events');
SELECT create_monthly_partitions('firewall_flows');
SELECT create_monthly_partitions('snmp_metrics');

-- Drop old partitions by retention (called from processor retention loop).
-- Drops entire partitions whose end bound is older than cutoff_days, which
-- is instant compared to row-by-row DELETE.
CREATE OR REPLACE FUNCTION drop_old_partitions(
    target_table TEXT,
    cutoff_days INT
) RETURNS INT AS $$
DECLARE
    r          RECORD;
    dropped    INT := 0;
    cutoff     TIMESTAMPTZ;
BEGIN
    cutoff := NOW() - (cutoff_days || ' days')::INTERVAL;
    FOR r IN
        SELECT c.relname AS part_name,
               pg_get_expr(c.relpartbound, c.oid) AS bound_expr
        FROM pg_inherits i
        JOIN pg_class c ON c.oid = i.inhrelid
        JOIN pg_class p ON p.oid = i.inhparent
        WHERE p.relname = target_table
        ORDER BY c.relname
    LOOP
        -- Extract the TO bound from "FOR VALUES FROM (...) TO (...)"
        -- and drop if the entire partition is before the cutoff.
        IF r.bound_expr ~ 'TO \(' THEN
            DECLARE
                to_val TEXT;
                to_ts  TIMESTAMPTZ;
            BEGIN
                to_val := SUBSTRING(r.bound_expr FROM 'TO \(''([^'']+)''\)');
                IF to_val IS NOT NULL THEN
                    to_ts := to_val::TIMESTAMPTZ;
                    IF to_ts <= cutoff THEN
                        EXECUTE FORMAT('DROP TABLE %I', r.part_name);
                        dropped := dropped + 1;
                    END IF;
                END IF;
            EXCEPTION WHEN OTHERS THEN
                NULL; -- skip unparseable partition bounds
            END;
        END IF;
    END LOOP;
    RETURN dropped;
END;
$$ LANGUAGE plpgsql;
