-- LogLM schema

-- Raw parsed events (recent window, older rows pruned by cron)
CREATE TABLE IF NOT EXISTS events (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    host        TEXT NOT NULL,
    source      TEXT NOT NULL,        -- syslog / nginx / firewall / snmp / librenms
    severity    TEXT NOT NULL,
    program     TEXT,
    message     TEXT NOT NULL,
    structured  JSONB DEFAULT '{}',
    verdict     TEXT NOT NULL         -- keep / store
);

CREATE INDEX idx_events_timestamp ON events (timestamp DESC);
CREATE INDEX idx_events_host ON events (host);
CREATE INDEX idx_events_source ON events (source);
CREATE INDEX idx_events_severity ON events (severity);

-- Alerts generated by LLM
CREATE TABLE IF NOT EXISTS alerts (
    id                  BIGSERIAL PRIMARY KEY,
    timestamp           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    severity            TEXT NOT NULL,
    title               TEXT NOT NULL,
    description         TEXT,
    affected_hosts      TEXT[],
    recommended_action  TEXT,
    false_positive_risk TEXT,
    event_count         INT,
    acknowledged        BOOLEAN DEFAULT FALSE,
    raw_result          JSONB DEFAULT '{}'
);

CREATE INDEX idx_alerts_timestamp ON alerts (timestamp DESC);
CREATE INDEX idx_alerts_severity ON alerts (severity);

-- Service aliases: map raw hostnames/IPs to friendly names
CREATE TABLE IF NOT EXISTS service_aliases (
    id          SERIAL PRIMARY KEY,
    raw_name    TEXT NOT NULL UNIQUE,  -- IP or hostname as it appears in logs
    alias       TEXT NOT NULL,         -- human-friendly name
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Service status derived from recent events
-- Updated by processor when a service's state changes
CREATE TABLE IF NOT EXISTS service_status (
    id              SERIAL PRIMARY KEY,
    service_name    TEXT NOT NULL UNIQUE,
    host            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'unknown',  -- ok / warning / error / unknown
    last_event      TIMESTAMPTZ,
    last_message    TEXT,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Chat conversations (memory system)
CREATE TABLE IF NOT EXISTS chat_sessions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       TEXT NOT NULL DEFAULT 'New conversation',
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          BIGSERIAL PRIMARY KEY,
    session_id  UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL,          -- user / assistant
    content     TEXT NOT NULL,
    context_summary TEXT,               -- snapshot of what the LLM was shown
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_session ON chat_messages (session_id, created_at);

-- Periodic summaries used as LLM memory / context compression
-- The analyzer writes one every N minutes summarising recent activity
CREATE TABLE IF NOT EXISTS memory_summaries (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    period_start TIMESTAMPTZ NOT NULL,
    period_end   TIMESTAMPTZ NOT NULL,
    summary     TEXT NOT NULL,
    key_events  JSONB DEFAULT '[]',     -- notable event IDs + one-liners
    stats       JSONB DEFAULT '{}'      -- event counts, top hosts, severity breakdown
);

CREATE INDEX idx_memory_summaries_ts ON memory_summaries (timestamp DESC);

-- SNMP metric history (rolled up from raw polls)
CREATE TABLE IF NOT EXISTS snmp_metrics (
    id          BIGSERIAL PRIMARY KEY,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    host        TEXT NOT NULL,
    sys_name    TEXT,
    avg_cpu     REAL,
    wifi_clients INT,
    interfaces_up   INT,
    interfaces_down INT,
    total_in_bps    REAL,
    total_out_bps   REAL,
    total_errors    REAL,
    raw_data    JSONB DEFAULT '{}'
);

CREATE INDEX idx_snmp_metrics_host_ts ON snmp_metrics (host, timestamp DESC);

-- Prune events older than 7 days (run via pg_cron or external cron)
-- To enable pg_cron: CREATE EXTENSION pg_cron;
-- SELECT cron.schedule('prune-events', '0 3 * * *', 'DELETE FROM events WHERE timestamp < NOW() - INTERVAL ''7 days''');
-- SELECT cron.schedule('prune-snmp', '0 3 * * *', 'DELETE FROM snmp_metrics WHERE timestamp < NOW() - INTERVAL ''30 days''');
-- SELECT cron.schedule('prune-memory', '0 3 * * *', 'DELETE FROM memory_summaries WHERE timestamp < NOW() - INTERVAL ''90 days''');
